import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Bento',
  description: 'Open-source project management — self-host or cloud.',
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,
  head: [
    ['link', { rel: 'icon', href: '/images/favicon.png' }],
    ['meta', { name: 'theme-color', content: '#0ea5e9' }],
  ],
  themeConfig: {
    logo: '/images/logo.svg',
    siteTitle: 'Bento',
    nav: [
      { text: 'Guide', link: '/guide/introduction' },
      { text: 'Self-Host', link: '/self-host/overview' },
      { text: 'User Guide', link: '/user-guide/overview' },
      { text: 'Architecture', link: '/architecture/overview' },
      { text: 'API', link: '/api/overview' },
      { text: 'Changelog', link: '/changelog' },
    ],
    sidebar: {
      '/guide/': [{ text: 'Getting Started', items: [
        { text: 'Introduction', link: '/guide/introduction' },
        { text: 'Quickstart', link: '/guide/quickstart' },
        { text: 'Core Concepts', link: '/guide/concepts' },
        { text: 'FAQ', link: '/guide/faq' },
      ]}],
      '/self-host/': [{ text: 'Self-Host', items: [
        { text: 'Overview', link: '/self-host/overview' },
        { text: 'Requirements', link: '/self-host/requirements' },
        { text: 'Docker Compose', link: '/self-host/docker-compose' },
        { text: 'Environment Variables', link: '/self-host/environment' },
        { text: 'Deployment Profiles', link: '/self-host/profiles' },
        { text: 'Reverse Proxy & TLS', link: '/self-host/reverse-proxy' },
        { text: 'Email (SMTP)', link: '/self-host/email' },
        { text: 'File Storage (MinIO)', link: '/self-host/storage-minio' },
        { text: 'Backup & Restore', link: '/self-host/backup' },
        { text: 'Updates', link: '/self-host/updates' },
        { text: 'Scaling', link: '/self-host/scaling' },
        { text: 'Troubleshooting', link: '/self-host/troubleshooting' },
      ]}],
      '/user-guide/': [
        { text: 'User Guide', items: [
          { text: 'Overview', link: '/user-guide/overview' },
        ]},
        { text: 'Account', collapsed: false, items: [
          { text: 'Register', link: '/user-guide/accounts/register' },
          { text: 'Verify Email', link: '/user-guide/accounts/verify-email' },
          { text: 'Login', link: '/user-guide/accounts/login' },
          { text: 'Forgot Password', link: '/user-guide/accounts/forgot-password' },
          { text: 'Profile', link: '/user-guide/accounts/profile' },
        ]},
        { text: 'Organizations', collapsed: true, items: [
          { text: 'Create', link: '/user-guide/organizations/create' },
          { text: 'Invite Members', link: '/user-guide/organizations/invite-members' },
          { text: 'Roles & Permissions', link: '/user-guide/organizations/roles' },
          { text: 'Switch Org', link: '/user-guide/organizations/switch-org' },
        ]},
        { text: 'Boards', collapsed: true, items: [
          { text: 'Create a Board', link: '/user-guide/boards/create' },
          { text: 'Columns & Workflow', link: '/user-guide/boards/columns' },
          { text: 'Labels', link: '/user-guide/boards/labels' },
          { text: 'Board Permissions', link: '/user-guide/boards/permissions' },
        ]},
        { text: 'Issues', collapsed: true, items: [
          { text: 'Create an Issue', link: '/user-guide/issues/create' },
          { text: 'Edit an Issue', link: '/user-guide/issues/edit' },
          { text: 'Assign & Estimate', link: '/user-guide/issues/assign' },
          { text: 'Comments & Mentions', link: '/user-guide/issues/comments' },
          { text: 'Attachments', link: '/user-guide/issues/attachments' },
          { text: 'Dependencies', link: '/user-guide/issues/dependencies' },
          { text: 'Time Tracking', link: '/user-guide/issues/time-tracking' },
          { text: 'My Issues', link: '/user-guide/issues/my-issues' },
        ]},
        { text: 'Sprints', collapsed: true, items: [
          { text: 'Overview', link: '/user-guide/sprints/overview' },
          { text: 'Plan a Sprint', link: '/user-guide/sprints/plan' },
          { text: 'Start a Sprint', link: '/user-guide/sprints/start' },
          { text: 'Close a Sprint', link: '/user-guide/sprints/close' },
        ]},
        { text: 'Views', collapsed: true, items: [
          { text: 'Backlog', link: '/user-guide/backlog' },
          { text: 'Timeline (Gantt)', link: '/user-guide/timeline' },
          { text: 'Global Timeline', link: '/user-guide/global-timeline' },
          { text: 'Calendar', link: '/user-guide/calendar' },
          { text: 'Inbox', link: '/user-guide/inbox' },
        ]},
        { text: 'Analytics', collapsed: true, items: [
          { text: 'Reports', link: '/user-guide/analytics/reports' },
          { text: 'Time Tracking', link: '/user-guide/analytics/time-tracking' },
        ]},
        { text: 'Settings', collapsed: true, items: [
          { text: 'Profile', link: '/user-guide/settings/profile' },
          { text: 'Security', link: '/user-guide/settings/security' },
          { text: 'Preferences (Language & Theme)', link: '/user-guide/settings/preferences' },
          { text: 'Members', link: '/user-guide/settings/members' },
          { text: 'Labels', link: '/user-guide/settings/labels' },
          { text: 'Integrations', link: '/user-guide/settings/integrations' },
          { text: 'Automations', link: '/user-guide/settings/automations' },
          { text: 'Org General', link: '/user-guide/settings/org-general' },
          { text: 'Org Advanced', link: '/user-guide/settings/org-advanced' },
        ]},
      ],
      '/architecture/': [{ text: 'Architecture', items: [
        { text: 'Overview', link: '/architecture/overview' },
        { text: 'Services', link: '/architecture/services' },
        { text: 'Data Model', link: '/architecture/data-model' },
        { text: 'Auth Flow', link: '/architecture/auth-flow' },
        { text: 'Events (Kafka)', link: '/architecture/events' },
        { text: 'Realtime (WebSocket)', link: '/architecture/realtime' },
        { text: 'Multi-tenancy', link: '/architecture/multi-tenancy' },
      ]}],
      '/api/': [{ text: 'API Reference', items: [
        { text: 'Overview', link: '/api/overview' },
        { text: 'Conventions', link: '/api/conventions' },
        { text: 'Auth Service', link: '/api/auth' },
        { text: 'Org Service', link: '/api/org' },
        { text: 'Board Service', link: '/api/board' },
        { text: 'Task Service', link: '/api/task' },
        { text: 'Notification Service', link: '/api/notification' },
        { text: 'Realtime Service', link: '/api/realtime' },
        { text: 'Attachment Service', link: '/api/attachment' },
      ]}],
      '/contributing/': [{ text: 'Contributing', items: [
        { text: 'Dev Setup', link: '/contributing/setup' },
        { text: 'Code Style', link: '/contributing/code-style' },
        { text: 'Testing', link: '/contributing/testing' },
        { text: 'Commit Conventions', link: '/contributing/commits' },
        { text: 'Pull Requests', link: '/contributing/pull-requests' },
      ]}],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/andreibel/bento' },
    ],
    editLink: {
      pattern: 'https://github.com/andreibel/bento/edit/main/website/:path',
      text: 'Edit this page on GitHub',
    },
    search: { provider: 'local' },
    footer: {
      message: 'Released under the AGPL-3.0 License.',
      copyright: 'Copyright © 2026 Andrei Beloziorov',
    },
  },
})
